# docker-compose up -d
# docker-compose down
# docker run --name my-mongodb -d --network=ecommerce-network -p 27105:27017 -v /Users/kiran/Desktop/docker-vol:/data/db mongo
# To build and image and push to repo
# docker login
# Create a repo
# docker build ukiras123/reponame .
# docker push ukiras123/reponame
version: "3"
services:
  admin-fe:
    container_name: admin-fe
    build:
      context: ./Admin/FE
      args:
        - VITE_API_URL=http://admin-checkin.beyondhimalayatech.com/api/api/v1
    ports:
      - "4000:4000"
    expose:
      - "4000"
    networks:
      - app_network
  admin-api:
    container_name: admin-api
    build:
      context: ./Admin/BE
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      - app_network
    volumes:
      - app_api_data:/usr/src/app/public/product/images
    env_file: ./Admin/BE/src/config/production.env
  client-fe:
    container_name: client-fe
    build:
      context: ./Client/FE
      args:
        - VITE_API_URL=http://client-checkin.beyondhimalayatech.com/api/api/v1
    ports:
      - "4001:4001"
    expose:
      - "4001"
    networks:
      - app_network
  client-api:
    container_name: client-api
    build:
      context: ./Client/BE
    ports:
      - "3001:3001"
    expose:
      - "3001"
    networks:
      - app_network
    env_file: ./Client/BE/config/production.env
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - admin-fe
      - admin-api
      - client-fe
      - client-api
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/config:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - app_network
  
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/config:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal -d client-checkin.beyondhimalayatech.com --email ukiras@gmail.com -d client-checkin.beyondhimalayatech.com -d admin-checkin.beyondhimalayatech.com --agree-tos

volumes:
  app_data:
  app_api_data:

networks:
  app_network:
